version: "3.7"

services:
  ce-bfh:
    build:
      dockerfile: Dockerfile
      context: .  
    container_name: ce-bfh
    image: ce-bfh
    tty: true
    tmpfs: /tmp
    volumes:
      - .:/ce-bfh
      - ./etc/gitconfig:/etc/gitconfig
    environment:
      - TZ=Europe/Berlin