---
title: "Robustness Checks | Corpus der Entscheidungen des Bundesfinanzhofs (CE-BFH)"
author: Seán Fobbe
geometry: margin=3cm
papersize: a4
fontsize: 11pt
output:
  pdf_document:
    toc: true
    toc_depth: 3
    number_sections: true
    pandoc_args: --listings
    includes:
      in_header: ../tex/Preamble_DE.tex
      before_body: [../temp/Definitions.tex, ../tex/Titlepage_Robustness.tex]
bibliography: ../temp/packages.bib
nocite: '@*'
---


```{r, setup, include=FALSE}
knitr::opts_chunk$set(fig.path = file.path("..", "analysis/"),
                      dev = config$fig$format,
                      dpi = config$fig$dpi,
                      fig.align = config$fig$align,
                      echo = TRUE,
                      warning = TRUE,
                      message = TRUE)

```


# Ergebnisse laden


```{r}
tar_load(latexdefs)
tar_load(dt.final)
tar_load(files.html)
tar_load(files.pdf)
tar_load(files.txt)

```





# Pipeline visualisieren



```{r, CE-BFH_00_Pipeline_Graph_karmesinrot, fig.width = 12, fig.height = 14, fig.pos = "p", fig.cap = "Der vollständige Prozess der Datensatz-Kompilierung."}


edgelist <- tar_network(targets_only = TRUE)$edges
setDT(edgelist)

g  <- igraph::graph.data.frame(edgelist,
                               directed = TRUE)

ggraph(g,
       'sugiyama') + 
    geom_edge_diagonal(colour = "#7e0731")+
    geom_node_point(size = 2,
                    color = "white")+
    geom_node_text(aes(label = name),
                   color = "white",
                   size = 2,
                   repel = TRUE)+
    theme_void()+
    labs(
        title = paste(prefix.figuretitle,
                      "| Vollständiger Prozess der Datensatz-Kompilierung"),
        caption = caption
    )+
    theme(
        plot.title = element_text(size = 14,
                                  face = "bold",
                                  color = "white"),                        
        plot.background = element_rect(fill = "black"),
        plot.caption = element_text(color = "white"),
        plot.margin = margin(10, 20, 10, 10)
    )

```







# Variablen

## Anzahl Variablen

```{r}
length(dt.final)
```


## Alle Namen der Variablen

```{r}
names(dt.final)
```


## Beispiel-Werte

```{r}
str(dt.final)
```







```{r, results = "asis"}
cat(readLines(tar_read(changelog)),
    sep = "\n")

```







# Parameter für strenge Replikationen


```{r}
system2("openssl", "version", stdout = TRUE)

sessionInfo()

```


# Literaturverzeichnis
